//
// Created by pranas on 1/24/2018.
//

#ifndef DATA_STRUCTURES_AND_ALGORITHMS_LOGGING_H
#define DATA_STRUCTURES_AND_ALGORITHMS_LOGGING_H


class logging {

};


#endif //DATA_STRUCTURES_AND_ALGORITHMS_LOGGING_H
