language: cpp
sudo: required

compiler:
    - g++

install:
    - wget --quiet -O - https://raw.githubusercontent.com/r-lyeh/depot/master/travis.pre.sh   | bash -x

before_script:
    - echo "Before script"
    - chmod +x ./Scripts/Travis/Build.bat
    - chmod +x ./Scripts/Travis/Run.bat

script:
    - pwd
    - ./Scripts/Travis/Build.bat
    - pwd
    - make -f ./Build/Test/Makefile
    - ls -lah ./Build/*
    - ./Scripts/Run.bat
